name: finances
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  share_plus: ^11.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  local_auth: ^3.0.1
  flutter_dotenv: ^6.0.1
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_apex.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_apex.png"
  adaptive_icon_background: "#EAF3F0"
  adaptive_icon_foreground: "assets/images/logo_apex.png"
